GET http://localhost:8880/hello
Accept: application/json



###

POST http://localhost:8880/hello/post
Content-Type: application/x-www-form-urlencoded

name=oyzg

###
GET http://localhost:8880/ebook/list
Accept: application/json


###

GET http://localhost:8880/redis/set/1232242342/test
Accept: application/json

###

GET http://localhost:8880/redis/get/9355951772025344
Accept: application/json